name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: jhipstertest pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            NODE_VERSION: 12.16.1
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - name: Invoke deployment hook
              uses: herzogf/workflow-webhook@v1.0.2-insecure
              env:
                webhook_url: ${{ secrets.WEBHOOK_URL }}
                webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
